/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginByCode: typeof import('./src/components/LoginByCode.vue')['default']
    LoginByPwd: typeof import('./src/components/LoginByPwd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YamlEditor: typeof import('./src/components/YamlEditor/index.vue')['default']
  }
}
